export { InsightsProvider } from './app/InsightsProvider.js'
export { getInsights } from './server/getInsights.js'
export { postHogMiddleware } from './middleware/postHogMiddleware.js'
export { InsightsPageView } from './client/InsightsPageView.js'
export { DEFAULT_INGEST_PATH } from './shared/constants.js'
export { useInsights, useFeatureFlag, useActiveFeatureFlags, InsightsFeature } from './client/hooks.js'
export type { InsightsProviderProps, BootstrapFlagsConfig } from './app/InsightsProvider.js'
export type { InsightsMiddlewareOptions, InsightsProxyOptions } from './middleware/postHogMiddleware.js'
