packages:
  - packages/*
  - packages/rrweb/*
  - packages/rrweb/plugins/*
  - tooling/*
  - "!**/playground/**"
  - "!**/examples/**"

catalog:
  '@hanzo/font': 1.9.2
  '@hanzo/insights': 1.358.1
  '@hanzo/insights-node': 6.0.0
  '@hanzo/react': 1.0.2

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - node-forge@1.3.2
  - next@15.5.7
  - "@next/env@15.5.7"
  - "@hanzo/rrweb-plugin-console-record@0.0.47"
  - "@hanzo/rrweb-record@0.0.47"
  - "@hanzo/rrweb-types@0.0.47"
  - "@hanzo/rrweb-utils@0.0.47"
  - "@hanzo/rrweb@0.0.47"
  - "@hanzo/rrweb-snapshot@0.0.47"
  - "@hanzo/rrdom@0.0.47"

supportedArchitectures:
  cpu: [x64, arm64v8, arm64]
  os: [linux, darwin]

blockExoticSubdeps: true
trustPolicy: no-downgrade
enableGlobalVirtualStore: true
